apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: console-banner
spec:
  backgroundColor: "{{ .Values.cluster.banner.bgColor }}"
  color: '#000'
  location: BannerTop
  text: {{ .Values.cluster.banner.text }}
